#!/bin/bash

# This is another example to show what a function could look like or do.
flower(){

# Echo command prints words to user.
echo "hello if you would like to see a pretty artistic flower then type flower"

# Cat command follow by two less than symbols will print out what ever is between the two 'EOF's end of file symbol.
	cat << EOF 
---------------------------------
........m......m.......m........
.......mm.....mmm.....mmm.......
.....mmmmm.mmmmmmm...mmmmm......
......mmm....mmmm....mmmm.......
.......mmmmmmmmmmmmmmmmmm.......
........mmmmmmmmmmmmmmmm........
............mmmmmmmm............
..............mmm...............
...............m................
...............m................
...............m................
...............m................
...............m................
---------------------------------
i picked this one fresh just for you
EOF

# This curly bracket here is the close to the function.
}

# This calls the function you dont actually type flower in this example its just a flower from the may program.
flower

# Holds user till enter press just in case not run from an already open terminal it wont do the open close so fast thing were you cant see it. 
read hold

# Last but not least an exit command to close.
exit

